name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Clean Install Dependencies
        run: npm run clean:install

      - name: |
          Create release pull request
          Run prepublishOnly script
          Run build script
          Verify changeset exists
          Publish package
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run changeset:publish
          setupGitUser: true
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify on Publish
        if: steps.changesets.outputs.published == 'true'
        run: echo "New version published!"
