name: Run on Tag Push

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.2.3

jobs:
  on-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Echo tag name
        run: echo "Triggered by tag $GITHUB_REF"
